var threesixty = new ThreeSixty(document.getElementById('threesixty'), {
  image: [
    'magic/magic_01.jpg',
    'magic/magic_02.jpg',
    'magic/magic_03.jpg',
    'magic/magic_04.jpg',
    'magic/magic_05.jpg',
    'magic/magic_06.jpg',
    'magic/magic_07.jpg',
    'magic/magic_08.jpg',
    'magic/magic_09.jpg',
    'magic/magic_10.jpg',
    'magic/magic_11.jpg',
    'magic/magic_12.jpg',
    'magic/magic_13.jpg',
    'magic/magic_14.jpg',
    'magic/magic_15.jpg',
    'magic/magic_16.jpg',
    'magic/magic_17.jpg',
    'magic/magic_18.jpg',
    'magic/magic_19.jpg',
    'magic/magic_20.jpg',
    'magic/magic_21.jpg',
    'magic/magic_22.jpg',
    'magic/magic_23.jpg',
    'magic/magic_24.jpg',
    'magic/magic_25.jpg',
    'magic/magic_26.jpg',
    'magic/magic_27.jpg',
    'magic/magic_28.jpg',
    'magic/magic_29.jpg',
    'magic/magic_30.jpg',
    'magic/magic_31.jpg',
    'magic/magic_32.jpg',
    'magic/magic_33.jpg',
    'magic/magic_34.jpg',
    'magic/magic_35.jpg',
    'magic/magic_36.jpg',
    'magic/magic_37.jpg',
    'magic/magic_38.jpg',
    'magic/magic_39.jpg',
    'magic/magic_40.jpg',
    'magic/magic_41.jpg',
    'magic/magic_42.jpg',
    'magic/magic_43.jpg',
    'magic/magic_44.jpg',
    'magic/magic_45.jpg',
    'magic/magic_46.jpg',
    'magic/magic_47.jpg',
    'magic/magic_48.jpg',
    'magic/magic_49.jpg',
    'magic/magic_50.jpg',
    'magic/magic_51.jpg',
    'magic/magic_52.jpg',
    'magic/magic_53.jpg',
    'magic/magic_54.jpg',
    'magic/magic_55.jpg',
    'magic/magic_56.jpg',
    'magic/magic_57.jpg',
    'magic/magic_58.jpg',
    'magic/magic_59.jpg',
    'magic/magic_60.jpg',
    'magic/magic_61.jpg',
    'magic/magic_62.jpg',
    'magic/magic_63.jpg',
    'magic/magic_64.jpg',
    'magic/magic_65.jpg',
    'magic/magic_66.jpg',
    'magic/magic_67.jpg',
    'magic/magic_68.jpg',
    'magic/magic_69.jpg',
    'magic/magic_70.jpg'
  ],
  aspectRatio: 1,
  count: 31,
  perRow: 4,
  speed: 100,
  prev: document.getElementById('prev'),
  next: document.getElementById('next'),
  inverted: true
});

// threesixty.play();

